[package]
name = "feast-server-core"
version.workspace = true
edition.workspace = true

[lib]
doctest = false


[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
prost = { version = "0.14.1", features = ["default", "derive"] }
prost-types = "0.14.1"
serde = { version = "1.0.219", features = ["default", "derive"] }
saphyr = { version = "0.0.6", features = ["default", "encoding"] }
async-trait = { version = "0.1.89" }
arc-swap = { version = "1.7.1" }
sqlx = { version = "=0.8.6", features = ["sqlite", "chrono", "runtime-tokio"] }
chrono = { version = "0.4.42", features = ["default", "serde"] }
aws-config = { version = "1.8.6", features = ["behavior-version-latest"] }
aws-sdk-s3={version = "1.106.0"}
url = "2.5.7"


[build-dependencies]
glob = { version = "0.3.3" }
prost-build = { version = "0.14.1", features = ["default"] }
